/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;

import backEnd.Articulos;
import backEnd.Planes;
import javax.swing.DefaultListModel;


/**
 *
 * @author Olivia Hernandez
 */
public class PrincipalCoppel extends javax.swing.JFrame {
    Articulos articulos = new Articulos();
    Planes planes = new Planes();
    String descripcion;
    double precio;
    /**
     * Creates new form PrincipalCoppel
     */
    public PrincipalCoppel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblNcuotas = new javax.swing.JLabel();
        cmbCodigo = new javax.swing.JComboBox<>();
        lblDes = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        rbPlan1 = new javax.swing.JRadioButton();
        rbPlan2 = new javax.swing.JRadioButton();
        rbPlan3 = new javax.swing.JRadioButton();
        rbPlan4 = new javax.swing.JRadioButton();
        lblPago = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltDetalleCuotas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNcuotas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNcuotas.setText("jLabel1");

        cmbCodigo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        cmbCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C001", "ST02", "M004", "L098" }));
        cmbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodigoActionPerformed(evt);
            }
        });

        lblDes.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblDes.setText("jLabel1");

        lblPrecio.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblPrecio.setText("jLabel1");

        buttonGroup1.add(rbPlan1);
        rbPlan1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        rbPlan1.setText("Plan 1");
        rbPlan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlan1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPlan2);
        rbPlan2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        rbPlan2.setText("Plan 2");
        rbPlan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlan2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPlan3);
        rbPlan3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        rbPlan3.setText("Plan 3");
        rbPlan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlan3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPlan4);
        rbPlan4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        rbPlan4.setText("Plan 4");
        rbPlan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlan4ActionPerformed(evt);
            }
        });

        lblPago.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblPago.setText("jLabel1");

        ltDetalleCuotas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jScrollPane1.setViewportView(ltDetalleCuotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbPlan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbPlan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbPlan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbPlan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblDes)
                        .addGap(35, 35, 35)
                        .addComponent(lblPrecio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPago)
                            .addComponent(lblNcuotas))
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDes)
                    .addComponent(lblPrecio))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPlan1)
                            .addComponent(lblPago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPlan2)
                            .addComponent(lblNcuotas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPlan3)
                        .addGap(18, 18, 18)
                        .addComponent(rbPlan4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodigoActionPerformed
        // TODO add your handling code here:
        descripcion = articulos.getDescripcion(cmbCodigo.getSelectedIndex());
        precio = articulos.getPrecio(cmbCodigo.getSelectedIndex());
        lblDes.setText(descripcion);
        lblPrecio.setText(String.valueOf(precio));
        
    }//GEN-LAST:event_cmbCodigoActionPerformed

    private void rbPlan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlan1ActionPerformed
        // TODO add your handling code here:
        double pagoFinal = planes.getPlan1(precio);
        lblPago.setText("Pago Final $ " + String.valueOf(pagoFinal));
        lblNcuotas.setText("Número de cuotas a pagar " + planes.getCuotas());
        ltDetalleCuotas.setListData(planes.getCuotas());
    }//GEN-LAST:event_rbPlan1ActionPerformed

    private void rbPlan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlan2ActionPerformed
        // TODO add your handling code here:
        double pagoFinal = planes.getPlan2(precio);
        lblPago.setText("Pago Final $ " + String.valueOf(pagoFinal));
        lblNcuotas.setText("Número de cuotas a pagar " + planes.getCuotas());
        ltDetalleCuotas.setListData( planes.getCuotas());
    }//GEN-LAST:event_rbPlan2ActionPerformed

    private void rbPlan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlan3ActionPerformed
        // TODO add your handling code here:
        double pagoFinal = planes.getPlan3(precio);
        lblPago.setText("Pago Final $ " + String.valueOf(pagoFinal));
        lblNcuotas.setText("Número de cuotas a pagar " + planes.getCuotas());
        ltDetalleCuotas.setListData( planes.getCuotas());
    }//GEN-LAST:event_rbPlan3ActionPerformed

    private void rbPlan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlan4ActionPerformed
        // TODO add your handling code here:
        double pagoFinal = planes.getPlan4(precio);
        lblPago.setText("Pago Final $ " + String.valueOf(pagoFinal));
        lblNcuotas.setText("Número de cuotas a pagar " + planes.getCuotas());
        ltDetalleCuotas.setListData( planes.getCuotas());
    }//GEN-LAST:event_rbPlan4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCoppel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCoppel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCoppel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCoppel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCoppel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCodigo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblNcuotas;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JList<String> ltDetalleCuotas;
    private javax.swing.JRadioButton rbPlan1;
    private javax.swing.JRadioButton rbPlan2;
    private javax.swing.JRadioButton rbPlan3;
    private javax.swing.JRadioButton rbPlan4;
    // End of variables declaration//GEN-END:variables
}
